safe_school_user:
    resource: "@SafeSchoolUserBundle/Resources/config/routing.yml"
    prefix:   /user

ss_app:
    resource: "@AppBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#inscription
api_inscription:
    resource: "@APIInscriptionBundle/Resources/config/routing.yml"
    prefix:   /inscription

#etablissement
api_etablissement:
    resource: "@APIEtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement

#information
api_info:
    resource: "@APIInfoBundle/Resources/config/routing.yml"
    prefix:   /information

#mediatheque
api_mediatheque:
    resource: "@APIMediathequeBundle/Resources/config/routing.yml"
    prefix:   /mediatheque

#note
api_note:
    resource: "@APINoteBundle/Resources/config/routing.yml"
    prefix:   /note

#statistiques
api_statistique:
    resource: "@APIStatistiqueBundle/Resources/config/routing.yml"
    prefix:   /statistique

#programme cours
api_programme:
    resource: "@APIProgrammeBundle/Resources/config/routing.yml"
    prefix:   /programme/{id_etablissement}

#exploit
api_exploit:
    resource: "@APIExploitBundle/Resources/config/routing.yml"
    prefix:   /exploit/{id_user}

# FOSUser Bundle resources
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
